### ISSUE TITLE
Bluez 5 support

### ISSUE THREAD

**Issue by direc85** [AsteroidOS/asteroidsyncservice#36]
It looks like Bluez 4 is not available anymore on X10II. This means e.g. `org.bluez.Manager` doesn't exist anymore, and the app and the service have to be updated accordingly.

I managed to sledgehammer `bluezclient.cpp` into such shape that I could see my lenok on the main page again (X10II aarch64 SFOS 4.2.0.21), but I can't get a battery reading nor anything else, not with the modded file + X10II, nor with unmodded file + XA2U (armv7hl SFOS 4.2.0.21).

A few disclaimers:

* I don't know Bluetooth
* I don't know DBus
* I'm tired and I don't really know what I'm doing
* It works (to some extent?) with Bluez 5

I attached the [bluezclient.cpp.txt](https://github.com/AsteroidOS/asteroidsyncservice/files/7192828/bluezclient.cpp.txt) in case you want to have a good laugh :upside_down_face: or have a look at it otherwise.

**Comment by GeoffTearle** [comment]
I've got some time off coming up soon so I'll try to see if I can get it working then.
I'm tempted to try and convert over to the QT bluetooth libs for this, as I think there are currently reconnection issues with the XA2 as well

**Comment by beroset** [comment]
I believe everything related to this has already been merged.  I've been using it with BlueZ 5 for some months.  Is there any remaining reason this shouldn't be closed?

**Comment by direc85** [comment]
When I last tried this with XA2, I couldn't get my watch to connect with the phone but with X10II it worked. I can test again now that both of them are running SFOS 4.4 (which may or may not include some updates wrt Bluez). Is it the current master I should test?

**Comment by beroset** [comment]
>  Is it the current master I should test?

Yes, I think the current master contains everything needed.  Thanks for testing!
